---
version: "3"
services:
 devopsdb:
   image: bharadwajbodda/mysecondrepo:mydbimg   
   ports:
     - "3306:3306"

 application:
   image: bharadwajbodda/mysecondrepo:myappimg
   container_name: containerapp
   ports:
     - "8666:8080"
   depends_on:
     - "devopsdb"
